vcf_file = "tests/data/test.vcf.gz"
test_with_multiple_variants = "tests/data/test_with_multiple_variants.vcf.gz"
sample_5kb_fasta_file = "tests/data/sample.5kb.fa"
gtf_file = "tests/data/sample.gtf"
example_intervals_bed = "tests/data/example_intervals.bed"
